language: go

go:
  - "1.9"
  - "1.10"
  - "tip"

script:
- go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: never
